CREATE TABLE IF NOT EXISTS nk_org (
    org_id BIGSERIAL PRIMARY KEY,
    org_name TEXT NOT NULL,
    x_5179 DOUBLE PRECISION NOT NULL,
    y_5179 DOUBLE PRECISION NOT NULL,
    geom_5179 GEOMETRY(Point,5179)
);

CREATE TABLE IF NOT EXISTS geojson (
    event_loc TEXT PRIMARY KEY,
    geometry GEOMETRY
);