"""
LangGraph state definitions for FINSIGHT.

This module defines the shared workflow state passed across the
multi-agent financial intelligence pipeline.

Pipeline overview:

User Request
    ↓
Manager Agent
    ↓
Parallel Worker Agents
    ├─ Macro Agent
    ├─ Markets Agent
    ├─ Commodities & FX Agent
    └─ Geopolitical Risk Agent
    ↓
Lead Analyst Agent
    ↓
Report Agent
    ↓
Final Briefing Output

The state acts as the system's shared working memory.

Each node reads from the current state and writes back only the fields
it is responsible for producing.
"""

from __future__ import annotations

from datetime import date
from typing import Any, TypedDict

from app.schemas.event import EventItem, RankedEventItem


class ManagerPlan(TypedDict, total=False):
    """
    Structured planning output generated by the Manager Agent.

    The manager interprets the user request, determines the date cutoff,
    country focus, and creates worker-specific task instructions.
    """
    date_cutoff: str
    country_focus: str
    report_type: str
    briefing_goal: str
    worker_tasks: dict[str, str]
    source_constraints: dict[str, list[str]]
    notes: list[str]


class AnalystSummary(TypedDict, total=False):
    """
    Structured summary produced by the Lead Analyst Agent.

    This contains the analyst's interpretation after collecting
    all worker outputs, removing duplicates, verifying evidence,
    and ranking events by country relevance and importance.
    """
    total_events_collected: int
    total_events_after_dedup: int
    top_themes: list[str]
    key_risks: list[str]
    cross_market_implications: list[str]
    watchlist: list[str]
    methodology_notes: list[str]


class FinanceBriefingState(TypedDict, total=False):
    """
    Global LangGraph state for the FINSIGHT workflow.

    Field groups:

    1. User input: Request parameters received from FastAPI
    2. Manager output: Planning data and worker task assignments
    3. Worker outputs: Raw event collections from each domain worker
    4. Analyst output: Merged, deduplicated, verified, and ranked events
    5. Final output: Human-readable market briefing
    6. Debug / operational metadata: Logs and error tracking
    """

    # 1. User input
    date: date
    country: str
    max_items_per_worker: int
    report_type: str

    # 2. Manager output
    manager_plan: ManagerPlan

    # 3. Worker outputs
    macro_events: list[EventItem]
    markets_events: list[EventItem]
    commodities_fx_events: list[EventItem]
    geopolitical_events: list[EventItem]

    # 4. Analyst output
    all_events: list[EventItem]
    deduplicated_events: list[EventItem]
    ranked_events: list[RankedEventItem]
    analyst_summary: AnalystSummary

    # 5. Final output
    report_markdown: str

    # 6. Debug / operational metadata
    logs: list[dict[str, Any]]
    errors: list[str]